# Generated by Django 4.2.1 on 2023-06-05 20:19

from django.db import migrations
from database.models.contribution_musical_work import ContributionMusicalWork
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth import get_user_model

def create_permission(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    content_type = ContentType.objects.get(app_label='database', model=ContributionMusicalWork._meta.model_name)

    # Check if the permission already exists
    permission, created = Permission.objects.get_or_create(
        codename='creation_access',
        content_type=content_type,
        defaults={
            'name': 'Can access creation forms',
        }
    )

    if created:
        User = get_user_model()
        superusers = User.objects.filter(is_superuser=True)
        for user in superusers:
            user.user_permissions.set([permission])

def remove_permission(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')

    Permission.objects.filter(codename='creation_access').delete()

def create_superuser(apps, schema_editor):
    User = get_user_model()
    User.objects.create_superuser(username='admin', email='admin@example.com', password='password')

class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'), 
    ]

    operations = [
        migrations.RunPython(create_permission, remove_permission),
        migrations.RunPython(create_superuser),
    ]
