# Generated by Django 2.0.8 on 2018-10-31 20:21

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='date',
            new_name='_date',
        ),
        migrations.AlterField(
            model_name='person',
            name='authority_control_url',
            field=models.URLField(blank=True, help_text='An URI linking to an authority control description of this Person', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='range_date_birth',
            field=django.contrib.postgres.fields.ranges.DateRangeField(blank=True, help_text='The birth year of this Person. The format is YYYY-MM-DD. If certain, put the beginning and end of the range as the same. If uncertain, enter a range that is generally accepted', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='range_date_death',
            field=django.contrib.postgres.fields.ranges.DateRangeField(blank=True, help_text='The death year of this Person. The format is YYYY-MM-DD. If certain, put the beginning and end of the range as the same. If uncertain, enter a range that is generally accepted', null=True),
        ),
        migrations.AlterField(
            model_name='sourceinstantiation',
            name='source',
            field=models.ForeignKey(help_text='The Source that this SourceInstantiation instantiates', on_delete=django.db.models.deletion.CASCADE, related_name='source_instantiations', to='database.Source'),
        ),
        migrations.AlterField(
            model_name='sourceinstantiation',
            name='work',
            field=models.ForeignKey(blank=True, help_text='The Musical Work manifested in part or in full by this Source Instantiation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_instantiations', to='database.MusicalWork'),
        ),
    ]
