# Generated by Django 2.0.8 on 2018-11-14 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20181031_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='certain',
            new_name='certainty_of_attribution',
        ),
    ]
