# Generated by Django 2.0.8 on 2018-11-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20181114_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='configuration_file',
            field=models.FileField(blank=True, help_text='A file that describes how the Software was configured when performing an encoding, validation or extracting task', null=True, upload_to='workflows/'),
        ),
    ]
