# Generated by Django 2.0.8 on 2019-03-21 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20190314_1808'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='featurefile',
            table='feature_file',
        ),
    ]
