# Generated by Django 2.0.8 on 2019-05-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20190503_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='certainty_of_attribution',
            field=models.NullBooleanField(help_text='Whether it is certain if this Person made this contribution'),
        ),
    ]
