# Generated by Django 2.0.8 on 2019-03-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20190321_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurefile',
            name='file',
            field=models.CharField(help_text='The actual file URL', max_length=300),
        ),
    ]
