# Generated by Django 2.0.8 on 2019-03-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20190322_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurefile',
            name='config_file',
            field=models.CharField(default='', help_text='The config file URL', max_length=300),
        ),
    ]
