# Generated by Django 2.0.8 on 2019-03-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_featurefile_config_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='file_type',
            field=models.CharField(help_text='The format of the File', max_length=100),
        ),
        migrations.AlterField(
            model_name='featurefile',
            name='file_type',
            field=models.CharField(help_text='The format of the File', max_length=100),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='file_type',
            field=models.CharField(help_text='The format of the File', max_length=100),
        ),
        migrations.AlterField(
            model_name='symbolicmusicfile',
            name='file_type',
            field=models.CharField(help_text='The format of the File', max_length=100),
        ),
        migrations.AlterField(
            model_name='textfile',
            name='file_type',
            field=models.CharField(help_text='The format of the File', max_length=100),
        ),
    ]
