# Generated by Django 2.0.8 on 2019-03-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20190323_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurefile',
            name='feature_definition_file',
            field=models.CharField(default='', help_text='The feature definition file URL', max_length=300),
        ),
    ]
