# Generated by Django 2.0.8 on 2019-03-29 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_featurefile_feature_definition_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbolicmusicfile',
            name='file',
            field=models.FileField(help_text='The actual file', upload_to='symbolic_music/', validators=[django.core.validators.FileExtensionValidator(['abc', 'krn', 'ly', 'mid', 'midi', '.xml'])]),
        ),
    ]
