# Generated by Django 2.0.8 on 2019-03-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20190329_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbolicmusicfile',
            name='file',
            field=models.FileField(help_text='The actual file', upload_to='symbolic_music/'),
        ),
    ]
