# Generated by Django 2.0.8 on 2019-04-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20190329_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchcorpus',
            name='features',
        ),
        migrations.AddField(
            model_name='researchcorpus',
            name='DOI_link',
            field=models.URLField(blank=True, help_text='An DOI linking to an research corpus saved in Zonedo ', null=True),
        ),
    ]
