# Generated by Django 2.0.8 on 2019-04-18 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20190418_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentalstudy',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='experimentalstudy',
            name='date',
        ),
        migrations.RemoveField(
            model_name='experimentalstudy',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='experimentalstudy',
            name='published',
        ),
    ]
