# Generated by Django 2.0.8 on 2019-04-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_auto_20190418_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchcorpus',
            name='DOI_link',
            field=models.URLField(blank=True, help_text='An DOI linking to an research corpus saved in Zenodo ', null=True),
        ),
    ]
