from database.views.viewsets import *
from database.views.autocomplete_views import StyleAutocomplete
from database.views.autocomplete_views import TypeAutocomplete
from database.views.autocomplete_views import GeographicAreaAutocomplete
from database.views.autocomplete_views import InstrumentAutocomplete
from database.views.autocomplete_views import SoftwareAutocomplete
from database.views.autocomplete_views import ArchiveAutocomplete
